### ISSUE TITLE
Error compiling greenlet

### ISSUE THREAD

**Issue by saghul** [pyston/pyston#1228]
Hi there!

I have a project which does a similar thing to the popular greenlet package, which replies on quite a few CPython specifics AFAIK.

Here is the compilation error on a fresh pyston Docker container:

```
(pyston_env)root@071f453deb0a:/src/greenlet# python run-tests.py
running build_ext
building 'greenlet' extension
creating build
creating build/temp.linux-x86_64-2.7
gcc -pthread -fno-strict-aliasing -O3 -DNDEBUG -fwrapv -Wall -Wstrict-prototypes -fPIC -I/pyston_env/from_cpython/Include -c -Werror=implicit-function-declaration greenlet.c -o build/temp.linux-x86_64-2.7/greenlet.o
greenlet.c: In function ‘g_switchstack’:
greenlet.c:462:30: error: ‘PyThreadState’ has no member named ‘frame’
   current->top_frame = tstate->frame;
                              ^
greenlet.c:463:29: error: ‘PyThreadState’ has no member named ‘exc_type’
   current->exc_type = tstate->exc_type;
                             ^
greenlet.c:464:30: error: ‘PyThreadState’ has no member named ‘exc_value’
   current->exc_value = tstate->exc_value;
                              ^
greenlet.c:465:34: error: ‘PyThreadState’ has no member named ‘exc_traceback’
   current->exc_traceback = tstate->exc_traceback;
                                  ^
greenlet.c:483:9: error: ‘PyThreadState’ has no member named ‘frame’
   tstate->frame = target->top_frame;
         ^
greenlet.c:485:9: error: ‘PyThreadState’ has no member named ‘exc_type’
   tstate->exc_type = target->exc_type;
         ^
greenlet.c:487:9: error: ‘PyThreadState’ has no member named ‘exc_value’
   tstate->exc_value = target->exc_value;
         ^
greenlet.c:489:9: error: ‘PyThreadState’ has no member named ‘exc_traceback’
   tstate->exc_traceback = target->exc_traceback;
         ^
greenlet.c: In function ‘g_calltrace’:
greenlet.c:510:8: error: ‘PyThreadState’ has no member named ‘tracing’
  tstate->tracing++;
        ^
greenlet.c:511:8: error: ‘PyThreadState’ has no member named ‘use_tracing’
  tstate->use_tracing = 0;
        ^
greenlet.c:513:8: error: ‘PyThreadState’ has no member named ‘tracing’
  tstate->tracing--;
        ^
greenlet.c:514:8: error: ‘PyThreadState’ has no member named ‘use_tracing’
  tstate->use_tracing = (tstate->tracing <= 0 &&
        ^
greenlet.c:514:31: error: ‘PyThreadState’ has no member named ‘tracing’
  tstate->use_tracing = (tstate->tracing <= 0 &&
                               ^
greenlet.c:515:33: error: ‘PyThreadState’ has no member named ‘c_tracefunc’
                         ((tstate->c_tracefunc != NULL) ||
                                 ^
greenlet.c:516:33: error: ‘PyThreadState’ has no member named ‘c_profilefunc’
                          (tstate->c_profilefunc != NULL)));
                                 ^
greenlet.c: In function ‘green_throw’:
greenlet.c:1106:41: error: dereferencing pointer to incomplete type
  ((PyObject *) ((PyInstanceObject *)(x))->in_class)
                                         ^
greenlet.c:1173:10: note: in expansion of macro ‘PyExceptionInstance_Class’
    typ = PyExceptionInstance_Class(typ);
          ^
error: command 'gcc' failed with exit status 1
Traceback (most recent call last):
  File "run-tests.py", line 41, in <module>
    spawn(cmd, search_path=0)
  File "/pyston-0.5.0-linux64/from_cpython/Lib/distutils/spawn.py", line 38, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/pyston-0.5.0-linux64/from_cpython/Lib/distutils/spawn.py", line 190, in _spawn_posix
    raise DistutilsExecError, \
distutils.errors.DistutilsExecError: command '/pyston_env/bin/python' failed with exit status 1
(pyston_env)root@071f453deb0a:/src/greenlet#
```

Since it's a quite popular package, and a dependency for gevent and eventlet, I thought I'd report here, with the hope that one day those can also run nicely on pyston.

Cheers!

**Comment by undingen** [comment]
Hi,
thanks for the report :+1:, I think no one of us has yes looked into this popular library.
From what `greenlet` is doing it looks like a more "invasive" library so I'm not to surprised it does not work yet :-( but they errors you got don't look too bad. For example instead of accessing `tstate->exc_type`,.. directly it should call `PyErr_GetExcInfo` instead when compiling for pyston. Some other fields we don't added yet because we don't support it. Like we will have to compile with the tracing support disabled because we don't support it yet.
So it's going to be some work and not trivial to get it to compile but it should not be to bad.
But than I really don't know if it will work after that because it could confuse our unwinding mechanism etc.. so it may need additional changes.

If someone is interested in working on this just post a comment into our gitter channel so we can discuss in more detail what to do.

**Comment by kmod** [comment]
Interesting!  It might be hard to support `g_switchstack` 100% unmodified, but it looks like it would be fairly easy to create a Pyston-specific version of that function (since on Pyston most of the function is unnecessary), which we could then host and/or try to upstream.

**Comment by saghul** [comment]
@kmod May doing something similar to what PyPy does would be a good idea here. They provide a greenlet module themselves because it also didn't work with their internals. Then you can ask the official greenlet package to skip installation on pyston. That way dependencies would be satisfied and libraries depending on it would Just Work (TM).
