### ISSUE TITLE
Error using networkx lib: AttributeError: 'function' object has no attribute '__closure__'

### ISSUE THREAD

**Issue by alanjds** [pyston/pyston#1263]
on Docker machine `pyston/pyston`, after `pip install networkx`:

``` bash
$ pyston -c "import networkx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/pyston_env/site-packages/networkx/__init__.py", line 84, in <module>
    import networkx.generators
  File "/pyston_env/site-packages/networkx/generators/__init__.py", line 5, in <module>
    from networkx.generators.classic import *
  File "/pyston_env/site-packages/networkx/generators/classic.py", line 21, in <module>
    from networkx.algorithms.bipartite.generators import complete_bipartite_graph
  File "/pyston_env/site-packages/networkx/algorithms/__init__.py", line 48, in <module>
    import networkx.algorithms.isomorphism
  File "/pyston_env/site-packages/networkx/algorithms/isomorphism/__init__.py", line 3, in <module>
    from networkx.algorithms.isomorphism.matchhelpers import *
  File "/pyston_env/site-packages/networkx/algorithms/isomorphism/matchhelpers.py", line 108, in <module>
    categorical_edge_match = copyfunc(categorical_node_match, 'categorical_edge_match')
  File "/pyston_env/site-packages/networkx/algorithms/isomorphism/matchhelpers.py", line 31, in copyfunc
    f.__closure__)
AttributeError: 'function' object has no attribute '__closure__'
```

**Comment by kmod** [comment]
Thanks for the report!  I fixed the issue you mentioned here in #1265, but even with that fix `import networkx` runs into other issues.
