### ISSUE TITLE
pyston 0.6 fails on django 1.10.3 test suite

### ISSUE THREAD

**Issue by dPeS** [pyston/pyston#1406]
```
./runtests.py 
Testing against Django installed in '/[...]/pyston-0.6.0-linux64/django/django' with up to 4 processes
Traceback (most recent call last):
  File "./runtests.py", line 485, in <module>
    failures = django_tests(
  File "./runtests.py", line 253, in django_tests
    state = setup(verbosity, test_labels, parallel)
  File "./runtests.py", line 215, in setup
    apps.set_installed_apps(settings.INSTALLED_APPS)
  File "/[...]/pyston-0.6.0-linux64/django/django/apps/registry.py", line 340, in set_installed_apps
    self.populate(installed)
  File "/[...]/pyston-0.6.0-linux64/django/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/[...]/pyston-0.6.0-linux64/django/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/[...]/pyston-0.6.0-linux64/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/[...]/pyston-0.6.0-linux64/django/tests/validation/models.py", line 137, in <module>
    assert str(assertion_error) == "A model can't have more than one AutoField."
AssertionError
```

steps to reproduce:

tar xaf pyston-0.6.0-linux64.tar.gz
cd pyston-0.6.0-linux64
./pyston virtualenv/virtualenv.py .
source bin/activate
pip install --upgrade pip
git clone https://github.com/django/django
cd django/
git checkout tags/1.10.3
cd tests/
pip install -e ..
pip install -r requirements/py2.txt
./runtests.py

on each pyston release I test django usability - this time starting project / app went fine, django admin works nice, time to pass django tests :)

**Comment by undingen** [comment]
thanks for the report!
I took a quick look and found some smaller issues which prevented the testsuite from running (the `id` thing is quite scary this is a probably a sign the testsuite does something shady...).
I put them into into https://github.com/dropbox/pyston/pull/1407, with this changes I'm able to run the testsuite with `--parallel 1` the result is:
```
Ran 11263 tests in 502.312s

FAILED (failures=34, errors=44, skipped=1127, expected failures=5)
```
Unfortunately I don't have time too look into the test failures but I'm sure there will be a few quick ones to so fix if someone has time and thinks this could be fun this may be something to look into :-).
